// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD3TNcmLJ9z92QlH6EmCPADDzuWeUinwc',
    appId: '1:1093411081699:android:074529b92f4bc94382e4d6',
    messagingSenderId: '1093411081699',
    projectId: 'healthyfast-f1f5a',
    storageBucket: 'healthyfast-f1f5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA8Ye9PMpzJSi2xPyCNvAfRsRbpK9A7Zg',
    appId: '1:1093411081699:ios:ac5ff56e4f546e1882e4d6',
    messagingSenderId: '1093411081699',
    projectId: 'healthyfast-f1f5a',
    storageBucket: 'healthyfast-f1f5a.firebasestorage.app',
    androidClientId: '1093411081699-an43b6bdag3c6hp0g91afgt2effkh8eu.apps.googleusercontent.com',
    iosClientId: '1093411081699-0rtct5jtid7vjogno1b8ei9pt6lvghbb.apps.googleusercontent.com',
    iosBundleId: 'co.healthyfast',
  );
}
